### ISSUE TITLE
Laravel configuration in readme file

### ISSUE THREAD

**Issue by itsmoto** [kizomanizo/safeclinica#1]
Hellow, 
Please add explaination about composer installation so that we can use these commands `php artisan migrate` and `php artisan db:seed`

**Comment by kizomanizo** [comment]
Hello!

The application has been updated. I have made the installation a tad more
simple by including a built-in installation process. I will update the
README file to explain the process.

All you need to do in search for a tool Xampp(you may have already
installed this). Once you have Xampp running with Apache and Mysql servers
started, you can clone the application inside C:\xampp\htdocs folder if you
are on Windows. If you are on Linux, install apache, php and mysql then
clone the application in /var/www/html Once the application has been cloned
or extracted there, just open your browser and open the application through
localhost/safeclinica/public it will open the installation page. The
installation has three steps only which need you to click the next step,
once done, it will be ready to use with username as *olympia* and password
as *olympia*.

[image: Inline image 1]

[image: Inline image 2]

[image: Inline image 3]

[image: Inline image 4]

*NB: *you can calso copy the file called .env.example and call it .env then
edit it with a text editor in the mysql section edit your credentials with
the database as safefocus and username root while the password is also
safefocus. If that is complex you can delete everything in the newly
created .env file and paste the following code inside.
https://pastebin.com/sNrmmZLR

Email me if you face any problems.



*Wakatabahu!*

*Bw. Kizito S.M.*
*Fieldwork Coordinator*
Hebet Technologies Ltd
Skype: kizoman
GTalk: kizomanizo
MSN: kizomanizo
Mob: +255 75 543 7887

**Comment by itsmoto** [comment]
Thank you
