### ISSUE TITLE
can't find model user (class app\user)

### ISSUE THREAD

**Issue by itsmoto** [kizomanizo/safeclinica#2]
Try to upload class app\user, I cant log in into system

**Comment by kizomanizo** [comment]
I have moved all models to another location called Models located in the
following namespace App\Http\Models. Therefore the User model should be in
that folder too!

*Wakatabahu!*

*Bw. **Kizito S.M.*
*Project Coordinator*
Softmed Tanzania Ltd
Skype: kizoman
Mob: +255 75 543 7887
